name:                datasaurus
version:             0.1.0.0
github:              "githubuser/datasaurus"
license:             BSD3
author:              "Ryan Jensen"
maintainer:          "jensenrj@sfasu.edu"
copyright:           "2019 Ryan Jensen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/datasaurus#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hmatrix
- hmatrix-gsl-stats
- random
- transformers
- hmatrix-csv
- bytestring
- reanimate >= 0.1.9.0
- diagrams-lib
#- diagrams-cairo

default-extensions:
- OverloadedLists
- FlexibleContexts
- TypeFamilies

library:
  source-dirs: src

executables:
  ds-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - datasaurus

tests:
  ds-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - datasaurus
    - QuickCheck
    - hspec
    build-tools: hspec-discover
